### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by windynoodles** [JoshAtticus/megi#5]
# markdown.
**pretty** _self_ `explanatory`

**Comment by windynoodles** [comment]
labels would be [client-side] and [enhancement] but i can't add labels i thignk

**Comment by JoshAtticus** [comment]
> # markdown.
> **pretty** _self_ `explanatory`

Was already planning on adding this, but will increase priority

**Comment by JoshAtticus** [comment]
Added with https://github.com/JoshAtticus/megi/commit/ab8088d97d967979042223395ec8a65115f76ceb

- `__text__` for underline
- `**text**` for bold
- `*text*` for italic
- `~~text~~ `for strikethrough
- `[text](url)` for links
