### ISSUE TITLE
Switch to a proper database

### ISSUE THREAD

**Issue by JoshAtticus** [JoshAtticus/megi#6]
JSON Databases are horrendously inefficient and require trimming every few thousand posts for performance reasons. Suggestions are welcome!

**Comment by davidtheplatform** [comment]
Does sqlite count as a proper database? It's really easy to set up/use and is more than powerful enough for this

**Comment by JoshAtticus** [comment]
> Does sqlite count as a proper database? It's really easy to set up/use and is more than powerful enough for this

Depends, I was thinking something like mongodb from a performance standpoint, but I could try sqlite

**Comment by davidtheplatform** [comment]
> > Does sqlite count as a proper database? It's really easy to set up/use and is more than powerful enough for this
> 
> Depends, I was thinking something like mongodb from a performance standpoint, but I could try sqlite

Is mongodb (or anything) more performant in a way that matters for this? There’s only one physical server so the fact that SQLite has to be on the same machine as the web server doesn’t matter

(I’m kind of biased as I’ve only really used SQLite)

**Comment by JoshAtticus** [comment]
> > > Does sqlite count as a proper database? It's really easy to set up/use and is more than powerful enough for this
> > 
> > 
> > Depends, I was thinking something like mongodb from a performance standpoint, but I could try sqlite
> 
> Is mongodb (or anything) more performant in a way that matters for this? There’s only one physical server so the fact that SQLite has to be on the same machine as the web server doesn’t matter
> 
> (I’m kind of biased as I’ve only really used SQLite)

I've personally never used SQLite but I'll look into it

**Comment by JoshAtticus** [comment]
I migrated the API to SQLite with the help of ChatGPT, seems to work well, just need to find a way to migrate the JSON database to an SQLite one. Code is at https://github.com/JoshAtticus/megi/blob/main/backend/api-sqlite.py

**Comment by JoshAtticus** [comment]
Added with https://github.com/JoshAtticus/megi/commit/80bf6caf85e1da72e2d3c41b91f8a51df4aba9be
