### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by windynoodles** [JoshAtticus/megi#9]
idk how or why but it's back for some reason

**Comment by davidtheplatform** [comment]
The anti xss code got replaced when markdown was added

**Comment by JoshAtticus** [comment]
> The anti xss code got replaced when markdown was added

grr

**Comment by JoshAtticus** [comment]
Should be fixed in https://github.com/JoshAtticus/megi/commit/0bfb9e8a042756ae534f5351b301a3a7f7a74bfe
